### ISSUE TITLE
Faster transitions

### ISSUE THREAD

**Issue by ghost** [dicksonleong/GagBook#1]
Great App! Please add faster transitions, current ones are kind of slow. Or maybe a slider in options to tune transition speed.

**Comment by dicksonleong** [comment]
The transition are performed by ListView internally so I can't modify it. But do you know you can swipe left and right to switch image? :)

**Comment by ghost** [comment]
me _facepalming_
Thanks for the swipe hint. Only tried the arrows. My bad.

**Comment by dicksonleong** [comment]
I still thinking to implement some visual hints that let the user know it is swipe-able. But still not able to figure it out yet...

**Comment by ghost** [comment]
What about hiding the < > arrows? Then swiping will seem to be the logic thing.

**Comment by dicksonleong** [comment]
If it do it like that I guess 90% of the user don't know it is swipe-able. Will removed the arrows once I implement a swipe-able visual hint

**Comment by ghost** [comment]
I guess you are right.
What about a first time screen as in here http://harmattan-dev.nokia.com/docs/ux/pages/Empty_States.html ?
There you could mention swipeability.

**Comment by dicksonleong** [comment]
Thanks for your suggestion but I don't think it is suitable implement in GagBook. I will try to figure out another way :)
