### ISSUE TITLE
are you porting this for sailfish?

### ISSUE THREAD

**Issue by cnlpete** [dicksonleong/GagBook#2]

**Comment by dicksonleong** [comment]
GagBook use QWebPage from QtWebkitWidgets (Qt5) to parse HTML and Sailfish does not support QtWidget (and thus, QtWebkitWidgets too). Simply creating a QWebPage and run on emulator cause a segmentation fault. Haven't got time to test on the latest Sailfish SDK update, but I doubt they will fix a bug for a module that they don't support.

One way is to use other third party html parser, but I can't find any suitable parser that is easy to use.

**Comment by dicksonleong** [comment]
Sailfish port done!

**Comment by cnlpete** [comment]
do you plan to put it in warehouse or store?

**Comment by dicksonleong** [comment]
Currently it is not possible to submit to Jolla store due to dependency on unsupported components (QtWidgets), so will probably put on OpenRepos for next release.
