### ISSUE TITLE
Login to 9GAG

### ISSUE THREAD

**Issue by jara001** [dicksonleong/GagBook#7]
Hi,
It looks like there is a problem with in-app 9GAG login system. I'm unable to log in (email and password are correct).

Thanks for this awesome app,
J.

**Comment by dicksonleong** [comment]
On which platform? There is a bug for Symbian (and probably Harmattan too), when typing password you need to wait the last character to become asterisk (`*`) before login, otherwise that character will be ignore.

**Comment by jara001** [comment]
I'm using latest Symbian on my 603. I tried it few times right now, still not working. I hope I'm doing everything in the right way, but on the other hand I don't think I can miss sth here. 
I also tried my login credetials right on 9gag - with no error.

**Comment by dicksonleong** [comment]
Try this: after finished typing your password, wait for 3 seconds, then close the virtual keyboard, then only click on the login button.

**Comment by jara001** [comment]
Still nothing :( - "Wrong username or password. Please try again."

**Comment by dicksonleong** [comment]
Looks like I have found the problem. Will fix it and push an update asap.

**Comment by dicksonleong** [comment]
Fixed in **[1.1.1](/dicksonleong/GagBook/releases/tag/v1.1.1)**. Please update and test again.

**Comment by jara001** [comment]
Everything is fine now, login is successful, thanks for update. :) J.
